export const teamMembers = [
  {
    id: 1,
    name: "Sahadat Mehedi Juine",
    role: "President",
    image: "/juine.webp",
    memberType: "Panel Member",
  },
  {
    id: 2,
    name: "MD Mahi Hamid Ratul",
    role: "Technology Editor",
    image: "/ratul.webp",
    memberType: "Panel Member",
  },
  {
    id: 3,
    name: "Naim Islam",
    role: "Financial Editor",
    image: "/naim.webp",
    memberType: "Panel Member",
  },
  {
    id: 4,
    name: "MD Hero",
    role: "Vice President",
    image: "/placeholder-user.jpg",
    memberType: "Panel Member",
  },
  {
    id: 5,
    name: "Shakil Hasan",
    role: "Secretary",
    image: "/placeholder-user.jpg",
    memberType: "Panel Member",
  },
  {
    id: 6,
    name: "Shahed Hasan",
    role: "Deputy Financial Editor",
    image: "/placeholder-user.jpg",
    memberType: "Panel Member",
  },
  {
    id: 7,
    name: "Ahammed Kochir",
    role: "International Affairs Editor",
    image: "/placeholder-user.jpg",
    memberType: "Panel Member",
  },
  {
    id: 8,
    name: "Mohammad Rafi",
    role: "Publicity Manager",
    image: "/placeholder-user.jpg",
    memberType: "Panel Member",
  },
  {
    id: 9,
    name: "Habib Ullah",
    role: "Deputy Publicity Editor",
    image: "/placeholder-user.jpg",
    memberType: "Panel Member",
  },
]
