export const teamMembers = [
  {
    id: 1,
    name: "Sahadat Mehedi Juine",
    role: "President",
    image: "/juine.webp",
    memberType: "Panel Member",
  },
  {
    id: 2,
    name: "MD Mahi Hamid Ratul",
    role: "Technology Editor",
    image: "/ratul.webp",
    memberType: "Panel Member",
  },
  {
    id: 3,
    name: "MD Hero",
    role: "Vice President",
    image: "/md-hero.webp",
    memberType: "Panel Member",
  },
  {
    id: 4,
    name: "Shakil Hasan",
    role: "Secretary",
    image: "/shakil-hasan.webp",
    memberType: "Panel Member",
  },
  {
    id: 5,
    name: "Sojib Hossain",
    role: "Joint Secretary",
    image: "/sojib-hossain.webp",
    memberType: "Panel Member",
  },
  {
    id: 6,
    name: "Ahammed Kochir",
    role: "International Affairs Editor",
    image: "/ahammed-kochir.webp",
    memberType: "Panel Member",
  },
  {
    id: 7,
    name: "Naim Islam",
    role: "Financial Editor",
    image: "/naim.webp",
    memberType: "Panel Member",
  },
  {
    id: 8,
    name: "Shahed Hasan",
    role: "Deputy Financial Editor",
    image: "/shahed-hasan.webp",
    memberType: "Panel Member",
  },
  {
    id: 9,
    name: "Mohammad Rafi",
    role: "Publicity Manager",
    image: "/mohammad-rafi.webp",
    memberType: "Panel Member",
  },
  {
    id: 10,
    name: "Habib Ullah",
    role: "Deputy Publicity Editor",
    image: "/habib-ullah.webp",
    memberType: "Panel Member",
  },
  {
    id: 11,
    name: "Md Foyeaz Islam",
    role: "Organizational Editor",
    image: "/foyeaz-islam.webp",
    memberType: "Panel Member",
  },
  {
    id: 12,
    name: "Afran Khan Shakil",
    role: "Deputy Organizational Editor",
    image: "/placeholder-user.jpg",
    memberType: "Panel Member",
  },
  {
    id: 13,
    name: "Ashraful Islam Limon",
    role: "Educational Affairs Editor",
    image: "/ashraful-islam-limon.webp",
    memberType: "Panel Member",
  },
]
